apiVersion: v1
kind: Service
metadata:
  name: demo-service
  labels:
    name: label1
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30001
    protocol: TCP
  selector:
    name: label1
