apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deploy
  labels:
    name: label1
spec:
  replicas: 2
  selector:
    matchLabels:
      name: label1
  template:
    metadata:
      name: my-pod
      labels:
        name: label1
    spec:
      containers:
        - name: cont2
          image: vamsibyramala/coffee-shop
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: 500Mi
              cpu: 100m
            requests:
              memory: 250Mi
              cpu: 80m
