apiVersion: v1
kind: ReplicationController
metadata:
  name: myreplications
spec:
  replicas: 2
  selector:
    name: label1
  template:
    metadata:
      name: myapp
      labels:
        name: label1
    spec:
      containers:
        - name: mycontainer
          image: vamsibyramala/test
          ports:
            - containerPort: 8080
